config/routes.rb
Rails.application.routes.draw do

  root "task#index"
  resources :task

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  def index
    @tasks = Task.all
    @tasks = @tasks.sort_by { |task| task.date }
  end

  def show 
    @tasks = Task.find(params[:id])
  end

  def new
    @tasks = Task.new(task_params)
    @tasks.save
  end



  private
  def task_params
      params.permit(:title, :descripton, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/task/index.html.erb
<h1> These are your task </h1>
<% @tasks.each do |t| %>
  <h2> <%= link_to t.title, task_path(t) %> 
    - <%= link_to t.date, task_path(t) %> </h2>

  <%end%>

<%= link_to "Create a new task", new_task_path %>

app/views/task/new.html.erb
<h1> Create a new task! </h1>

<%= form_for @tasks, url: {action: "create"} do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :descripton %>
  <%= f.text_field :date %>
  <%= f.submit "Create" %>
<% end %>

app/views/task/show.html.erb
<h1> <%=@tasks.title%> </h1>

<p> <%=@tasks.description%> </p>

<%= link_to "Back to all tasks", root_path %>